//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

	public enum AbilityNames
	{
		STRENGTH = 1, DEXTERITY = 2, CONSTITUTION = 3, INTELLIGENCE = 4, WISDOM = 5, CHARISMA = 6
	}


